name: Deploy to AWS with terraform

on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest #terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    steps:
      - name: checkout repository.
        uses: actions/checkout@v2

      # - name: setup Github OIDC
      #   run: |
          



      # - name: configure AWS credentials using OIDC
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{secrets.AWS_GITHUB_ROLE}} 
      #     aws-region: ${{secres.AWS_REGION}}
      #     audience: sts get-caller-identity
      # - run: aws sts get-caller-identity



      - name: configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # removed role-to-assume as requested
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: 'install TFLint'  
      #   run: |
      #     curl

      #     ./tflint --version  

      - name: 'install tfsec for security scanning'
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version

         
          
          
          

      - name: 'terraform init'
        run: terraform init

      - name: 'terraform format' 
        run: terraform fmt 

      - name: 'terraform validate'
        run: terraform validate

      # - name: 'TFLint'  
      #   run: |
      #     ./tflint --init
      #     ./tflint       
      
      - name: 'tfsec'
        run: tfsec . || true

      - name: 'terraform plan'
        run: terraform plan

      - name: 'terraform apply'
        run: terraform apply --auto-approve

      # - name: 'terraform destroy'
      #   run: teraform destroy --auto-approve      



